#ifndef _RENDER_ENGINE_COMMON_H_
#define _RENDER_ENGINE_COMMON_H_

#define TEXT_ALIGN_HORZ_LEFT 0
#define TEXT_ALIGN_HORZ_CENTER 1
#define TEXT_ALIGN_HORZ_RIGHT 2

#define TEXT_ALIGN_VERT_CENTER 0

#endif