#ifndef USER_DEFINED_MSG_H
#define USER_DEFINED_MSG_H

#define MSG_ACTIVE_PAGE WM_USER + 1

#define MSG_ACTIVE_TAB WM_USER + 2

#define MSG_GRID_POPUP_MENU_BEGIN 4096
#define MSG_GRID_POPUP_MENU_END 4098

#endif
